### ISSUE TITLE
v25 QA volunteer thread

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1766]
v25 rewrites a *lot* of things:

  * the local DB (flat .json files => sqlite)
  * how butler is used (one-off execs => daemon)
  * the whole install/configure/launch/prereqs/logic
  * all three sandboxes
  * a lot of the UI code
  * how some dependencies are served (gcs+cloudflare => download service+CDN)
  * etc.

I've tried to make sure that everything still works as expected, and wrote a ton of tests (still have two tons to write) - but I'm opening this issue so that folks who want to help me test beta builds have some way to be notified when I'm ready for them.

This includes all folks who got curious when I mentioned all the great stuff in "the next stable release" for, uhhh almost a year now.

**If you want to be part of the QA round, comment here (visible) or just subscribe to this issue (invisible)**. Thanks! :star2:

**Comment by quyse** [comment]
@fasterthanlime I tried master branch, and the first problem: captcha window shown after entering credentials is completely empty. So no way to log into the app.

**Comment by fasterthanlime** [comment]
@quyse Thanks, I just pushed a fix for that. In order to avoid spamming this thread (which is going to be used mostly for announcements), maybe open up new issues? You can group a few related ones together if you want to keep bookkeeping lower :)

**Comment by forest-hermit** [comment]
Subscribed, where I could download this test version? :)

**Comment by fasterthanlime** [comment]
Ohey what's this :package: :tada: :shipit:

  * https://fasterthanlime.itch.io/install-kitch

(There's a built-in report tool)

I'll do a proper reach-out later in the week, just curious to see if anyone picks this up from this comment alone! /cc @itchio/testers

**Comment by forest-hermit** [comment]
Thanks @fasterthanlime I test it right now and this bug still happens with the latest kitch.

**Comment by fasterthanlime** [comment]
@forest-hermit I'm not sure which issue you're talking about :)

Please open new issues (or comment on the existing ones) instead of replying to this thread. Thanks!

(edit: Oh, the kde tray icon thing. I'll take a look!)

**Comment by forest-hermit** [comment]
@fasterthanlime the dangers of posting tired at night haha. I will post it here:

> no tray icon on KDE #1106 

Where it belongs :)

**Comment by fasterthanlime** [comment]
The beta is public now 🌟 https://twitter.com/fasterthanlime/status/1016638163819868160

closing this
