### ISSUE TITLE
Itch app prevents Windows sleep

### ISSUE THREAD

**Issue by jleen** [itchio/itch#2293]
The Itch app sometimes prevents my Windows system from sleeping. The symptom is that the laptop will simply remain awake and drain its battery. I know it's the Itch client at fault because:

C:\>powercfg /requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume3\Users\jleen\AppData\Local\itch\app-25.4.0\itch.exe
Electron

I am running itch 25.4.0 with butler 15.12.0 and itch-setup 1.18.0. I have "Prevent display sleep while playing", but no games are playing, and disabling the toggle does not cause the powercfg report to clear. Closing the Itch app (really quitting, not just minimizing to the notification area) does clear the powercfg report. The issue does not happen all the time; it seems to crop up after the itch client has been running for a while. I'm happy to provide any logs that might be helpful.

**Comment by kg** [comment]
Just had this problem as well. My PC was idle with all input devices unplugged at the lock screen for about 12 hours and never slept, when I came back and dug around I determined that the cause was itch minimized to the notification area. I played a game using itch as the launcher maybe 24 hours ago. Closing it and locking the PC again allowed it to sleep right away.

itch 25.4.0, butler 15.17.0, itch-setup 1.18.0

Prevent display sleep while playing is also enabled. I assume this is the default, I don't remember turning it on

**Comment by kg** [comment]
From testing, all I need to do is launch World of Horror and itch.exe acquires a DISPLAY lock and never releases it. I tried launching and exiting some other games and the lock was not released.

**Comment by fasterthanlime** [comment]
Yep seems like that's still an issue. I don't understand why yet, because this code exists:

https://github.com/itchio/itch/blob/adbb1b004b39ab42f292893e062b15b096a46e09/src/main/reactors/launch/perform-launch.ts#L301-L303

so it *should* stop blocking powersave, but clearly it doesn't, so, something to keep in mind for v26, which I'm hoping to release any week now..

**Comment by kg** [comment]
Looking at the source for this API on Windows, it seems like there are a bunch of silent failure scenarios.

https://chromium.googlesource.com/chromium/src/+/66.0.3359.158/services/device/wake_lock/power_save_blocker/power_save_blocker_win.cc
https://github.com/electron/electron/blob/master/shell/browser/api/electron_api_power_save_blocker.cc

It's awkward but you may want to call the relevant APIs directly, at least on Windows. I'm not sure I'd trust the Mac or Linux implementations either given how it's written but maybe they work.

**Comment by fasterthanlime** [comment]
I wouldn't be surprised that that's the case, for now I want to leave the benefit of the doubt and hope that maybe I was misusing it, or that it has been fixed by Electron in later versions.

If we end up having to call platform-specific APIs ourselves, then so be it. That's already why 80% of the app's functionality lives in butler instead of the TypeScript/electron repo..

**Comment by joaociocca** [comment]
so, the only workaround for now is to close the app before leaving?

**Comment by UndarkAido** [comment]
It'd be very nice to have a fix for this, especially since the itch app is meant to stay open in the background

**Comment by Tridon** [comment]
This issue still exists in version 25.6.2.

**Comment by Novex** [comment]
Still exists in 26.1.9

I found that unticking the `Prevent display sleep while playing` option seems to work around the issue though

**Comment by roberto-gigli** [comment]
Still happening, in Itch 26.1.9, the workaround mentioned by @Novex works tho, 
`sudo powercfg.exe /requests` Reveals that after turning that option off (and restarting itch), it no longer requests the display to stay on
