### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by LennyPhoenix** [itchio/itch#2771]
When attempting to run `~/.itch/app-25.5.1/itch`, the following error occurs:

```
14:29:48.799 INFO itch@25.5.1 on electron@10.4.5 in production
14:29:48.800 DEBUG (m/reac/preb/load-preferences) imported preferences: {"downloadSelfUpdates":true,"offlineMode":false,"installLocations":{},"defaultInstallLocation":"appdata","isolateApps":false,"closeToTray":true,"readyNotification":true,"showAdvanced":false,"openAtLogin":false,"openAsHidden":false,"manualGameUpdates":false,"preventDisplaySleep":true,"preferOptimizedPatches":false,"disableBrowser":false,"enableTabs":false}
14:29:48.908 DEBUG (m/reac/preb/load-preferences) imported preferences: {"downloadSelfUpdates":true,"offlineMode":false,"installLocations":{},"defaultInstallLocation":"appdata","isolateApps":false,"closeToTray":true,"readyNotification":true,"showAdvanced":false,"openAtLogin":false,"openAsHidden":false,"manualGameUpdates":false,"preventDisplaySleep":true,"preferOptimizedPatches":false,"disableBrowser":false,"enableTabs":false}
14:29:48.913 DEBUG (m/net/register-itch-protocol) Registering itch: protocol for session with user agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) itch/25.5.1 Chrome/85.0.4183.121 Electron/10.4.5 Safari/537.36
14:29:49.119 INFO (m/reac/preboot) preboot ran in 211.00ms
14:29:49.121 DEBUG (m/reac/open-at-login) Updating login item settings, open=false, hidden=false
14:29:49.121 DEBUG (m/reac/open-at-login) Copying /usr/share/applications/io.itch.itch.desktop => /home/lenny/.config/autostart/io.itch.itch.desktop
14:29:49.124 DEBUG (m/reac/winds) Waiting on root window to dispatch boot
14:29:49.914 INFO (m/reac/i18n) Language settings: preference undefined, sniffed en-GB, fallback en
14:29:49.917 DEBUG (m/reac/locales) Reading local locale file /home/lenny/.itch/app-25.5.1/resources/app/src/static/locales/en.json
14:29:49.920 DEBUG (m/reac/locales) Reading remote locale file /home/lenny/.itch/app-25.5.1/resources/app/src/static/locales/en.json
[29288:0221/142951.078477:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

When running the application any other way, the window appears then immediately disappears with no error.

# System Info

- Arch Linux (Endeavour OS)
- Not using a DE: BSPWM
- Itch 25.5.1, installed via [Itch Installer](https://itch.io/app/download?platform=linux)

**Comment by arisu-gh** [comment]
There was a glibc update in Arch that broke a lot of electron apps. In order to fix it looks like electron needs to be upgraded to version 14 or higher.
more info here
https://github.com/electron/electron/pull/31091

I tried to manually update it to a newer electron version which got the renderer to run, but it wouldn't load the login page.

**Comment by LennyPhoenix** [comment]
After installing electron14 I'm still getting the crash :/

**Comment by arisu-gh** [comment]
I don't know much about electron or nodejs, so I wouldn't really know how to fix up itch to properly use a newer electron version. So for me I'm just going to keep Arch downgraded until more electron apps get fixed

**Comment by arisu-gh** [comment]
I was able to get it to run on the latest glibc by running itch without a sandbox
--no-sandbox
so at least there's a workaround for now

**Comment by m00nwtchr** [comment]
Another solution is to use `electron11`
Just installing a different electron version won't work, though, since itch normally ships with its own compiled version, but i made an AUR package which uses this one: `itch-bin` (https://aur.archlinux.org/packages/itch-bin)

You can also launch it manually like this: `electron11 ~/.itch/app-25.5.1/resources/app/`

(Note: it looks like an error message does appear if you have the web browser enabled, but the app works fine if you just leave it alone, don't click any of the buttons on the pop-up)

**Comment by arisu-gh** [comment]
the AUR package works great! Thank you
Edit: actually it crashes quite a bit

**Comment by m00nwtchr** [comment]
@ArisuUWU
Do you get a message with three buttons? (with the title `The application has crashed`) or does it just close?
if the former, just move it aside and check if you can still use the main itch app

EDIT: Looks like using the web browser causes it to close instantly, but you can still use other parts of the app.

**Comment by arisu-gh** [comment]
@m00nwtchr 
I was able to get it to work without crashing by setting some variables in main.bundle.js 
This is hacky and breaks some things. It for sure breaks games tagged as "Play In Browser", but as far as I can tell it works for everything else.
[patch.zip](https://github.com/itchio/itch/files/8201526/patch.zip)

**Comment by m00nwtchr** [comment]
Thanks! I added the patch to the aur package.

**Comment by leafo** [comment]
Thanks for the workarounds everyone, we're working on getting updated builds out in the near future.

**Comment by serjor** [comment]
> I was able to get it to run on the latest glibc by running itch without a sandbox --no-sandbox so at least there's a workaround for now

Unfortunately, this workaround doesn't work for openSUSE tumbleweed. I tried that and I only get a black screen

**Comment by hdansin** [comment]
Can confirm that this affects Solus too, running with `--no-sandbox` got it to launch.

**Comment by adamdmoss** [comment]
affects ubuntu 22 too, `--no-sandbox` got it to launch

**Comment by afettouhi** [comment]
Still an issue on Arch Linux but `--no-sandbox` works.

**Comment by acook** [comment]
Also on Solus,  hardware acceleration flag has no effect, only the `--no-sandbox` option allows the app to run.

**Comment by mboeder-2306** [comment]
Can also confirm on Linux Mint 21.1 Cinnamon : `~/.itch/itch --no-sandbox` works as a workaround.

**Comment by deus369** [comment]
it's been 2 years, can it somehow be fixed in the installer?

confirmed buggy still on Ubuntu 23.04

**Comment by volnes** [comment]
2024 issue still here

**Comment by mortoray** [comment]
Still an issue.

**Comment by sjkillen** [comment]
Can only launch with --no-sandbox using Ubuntu 24.04.1

**Comment by starichkov** [comment]
Still an issue in 2025, Ubuntu 24.10. It only works with `--no-sandbox`.

**Comment by leafo** [comment]
This issue should be resolved with the most recent version via an Electron update. Please leave a comment if you are still having this issue on app version 26.9.0 or above.
